FROM python:3.8.10

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# pip installs
COPY ./backend/requirements.txt ./app/requirements.txt
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install -r ./app/requirements.txt

WORKDIR /app